# we just need to import codecov working library workkflow

name: Python Code cov
on: ['push', 'pull_request'] # This code cov yaml file will trigger every time there is a push or pull request to the repository (on any branch)



jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out 
              uses: actions/checkout@v3 # makes a copy of our repository on the runner machine, which is an Ubuntu server provided by GitHub Actions

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install pytest coverage  #code cov has this library called coverage, which is used to measure code coverage
                pip install -r session_7_CD/requirements.txt

            - name: Run tests
              run: |
                coverage run -m pytest # coverage will run the pytest and creates an xml file with the coverage report
                coverage xml # this is used to upload the coverage report to Codecov website

            - name: Upload coverage artifact
              uses: actions/upload-artifact@v4 # after xml file is created we can upload it to Github Action Storage using this function
              with:  # usong this function we can upload any file.
                name: coverage
                path: coverage.* # this will upload the coverage.xml file to the GitHub Actions storage, which can be used later in the workflow

# go to codecov.com to get the token, which is used to authenticate the upload of coverage report to Codecov

# download the coverage file and upload to codecov
    coverage:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Check out
              uses: actions/checkout@v3

            - name: Download coverage artifact
              uses: actions/download-artifact@v4 # downlaod artifact from the previous job which we have dumped. we're downloading it to ubuntu server. This ubuntu is different from the 1st one
              with:
                  name: coverage

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: coverage.*